""" My Final code!
Written by Katelyn Gee
14/04/2022"""

# importing random generator
import random


# yes/no checker function goes here:
def yes_no(asking):
    while True:
        # Ask user if they have played the game in the past
        question = input(asking).lower()

        # If yes, calling on game function
        if question == "y" or question == "yes":
            question = "Yes"
            return question

        # If no, calling on instruction function
        elif question == "n" or question == "no":
            question = "No"
            return question

        # If incorrect input, repeat questions
        else:
            print("Incorrect input, please enter yes or no (y/n).")


# function to display instructions
def instructions():
    print(formatting("*", "How to play"))
    print()
    print("At the next questions, you will enter how much money "
          "you wish to play the game with. Each round costs $1 "
          "and each round, you get a token that is randomly "
          "generated by the computer that could win you back your money. "
          "The token could either be a DONKEY - where you get nothing - "
          "a HORSE or ZEBRA - where you get 50 cents - or a UNICORN - "
          "where you get $5!! Each round, you get the choice "
          "to leave the game and keep the money you have got left "
          "by enter 'X' or continuing to the next round by hitting <enter>")
    print()


# Number checking functions
def number_checker(question, low, high):
    error = "Error, try again! Please enter a whole number between 1 and 10."

    # Keeps asking until the correct value is entered
    while True:
        try:
            # asking the question
            print()
            amount = int(input(question))

            # checking if the number is between the required amount
            if low <= amount <= high:
                return amount
            else:
                print(error)

        except ValueError:
            # print error if not a valid integer
            print(error)


# looping rounds function
def looping_rounds(money):

    # starting variable for loop
    play_again = ""
    rounds = 0

    # function to generate a random token
    while play_again != "x":

        # adding one to rounds to make it the right round number
        rounds += 1

        # output the round it is
        print("--------------------------------------------------")
        print()
        print(f"Round {rounds}:")
        print()

        # Take off $1 to play the game
        money -= 1
        # Computer choice a random
        computer_choice = random.randint(1, 100)
        if computer_choice <= 5:

            # There is a 5% chance the random number will be under 5.
            # If that happens, unicorn is token
            money += 5
            print(formatting("!", "Congratulations, you got a unicorn"))
            print()
        elif 6 <= computer_choice <= 35:

            # There is a 30% chance the random number will be between 6 and 35.
            # If that happens, Donkey is token
            print(formatting("D", "Bad Luck, you got a Donkey"))
            print()

        else:
            # Making a list to print a random of zebra or horse
            random_token = ["Zebra", "Horse"]

            # token is randomly selected from horse or zebra
            final_choice = random.choice(random_token)

            # Finding out which animal to print
            if final_choice == "Zebra":
                print(formatting("Z", "You got a Zebra"))
                print()
            else:
                print(formatting("H", "You got a Horse"))
                print()
            money += 0.5

        # prints the token and final money count of each token for testing
        print(f"Your balance is now ${money}")
        print()
        if money <= 1:
            play_again = "x"
            print("Sorry, you ran out of money")
        else:
            # asking the user if they want to continue
            play_again = input(f"Hit enter if you want to "
                               f"continue to round {rounds + 1}? "
                               f"If you want to quit enter 'x': ")
    return money


# function to format text output
def formatting(symbol, sentence):
    sides = symbol * 3
    sentence_style = f"{sides} {sentence} {sides}"
    symbol_style = symbol * len(sentence_style)
    return f"{symbol_style}\n{sentence_style}\n{symbol_style}"


# start of game welcome
print(formatting("-", "Welcome to Lucky Unicorn Game"))
print()

# Yes/No checker main routine
played_before = yes_no("Do you know how to play this game "
                       "(Lucky Unicorn)? Y/N ")

if played_before == "No":
    instructions()


# How much checker main routine
print()
user_balance = number_checker('Enter the amount of money you want to '
                              'play with between 1 and 10: $', 1, 10)
print(f"You are using ${user_balance}")


# Looping main routine by Print the start balance and what the user ended with
final_balance = looping_rounds(user_balance)
print("---------------------------------------")
print("Thanks for playing!")
print(f"You starting balance was {user_balance:.2f} ")
print(f"You final balance is ${final_balance:.2f}")
print()
print(formatting("*", "Goodbye"))
